import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [blocks, setBlocks] = useState([]);
  const [editing, setEditing] = useState(null);

  useEffect(() => {
    getBlocks();
  }, []);

  // Create
  const onSubmitBlock = async (e) => {
    e.preventDefault();
    const { title, author, description } = e.target;
    await axios.post("/api/blocks", {
      title: title.value,
      author: author.value,
      description: description.value,
    });
    title.value = "";
    author.value = "";
    description.value = "";
    getBlocks();
  };

  // Read
  const getBlocks = async () => {
    const res = await axios.get("/api/blocks");
    const data = res.data;
    setBlocks(data);
  };

  // Update
  const onSubmitEdits = async (e, id) => {
    e.preventDefault();
    const { title, author, description } = e.target;
    await axios.post(`/api/blocks/update/${id}`, {
      title: title.value,
      author: author.value,
      description: description.value,
    });
    setEditing(null);
    getBlocks();
  };

  // Delete
  const deleteBlock = async (blockToDelete) => {
    await axios({
      method: "DELETE",
      url: "/api/blocks/",
      data: {
        id: blockToDelete,
      },
    });
    await getBlocks();
  };

  return (
    <div className="App">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="DataInput">
        <h2>Enter block:</h2>
        <form onSubmit={(e) => onSubmitBlock(e)}>
          <label htmlFor="title">Title:</label>
          <input type="text" name="title" />
          <label htmlFor="author">Author:</label>
          <input type="text" name="author" />
          <label htmlFor="description">Description:</label>
          <input type="text" name="description" />
          <button>Add Block</button>
        </form>
      </div>
      <div className="DataOutput">
        {blocks.map((block) => (
          <div key={block._id}>
            {editing !== block._id ? (
              <div key={block._id} className="DataOutput__card">
                <div className="DataOutput__card--details">
                  <div>
                    <span>Title:</span>
                    {block.title}
                  </div>
                  <div>
                    <span>Author:</span>
                    {block.author}
                  </div>
                  <div>
                    <span>Description:</span>
                    {block.description}
                  </div>
                </div>
                <div className="DataOutput__card--options">
                  <button onClick={() => setEditing(block._id)}>Edit</button>
                  <button onClick={() => deleteBlock(block._id)}>Delete</button>
                </div>
              </div>
            ) : (
              <div key={block._id} className="DataOutput__editing">
                <form onSubmit={(e) => onSubmitEdits(e, block._id)}>
                  <div className="DataOutput__editing--option">
                    <label htmlFor="title">Title:</label>
                    <input
                      type="text"
                      name="title"
                      defaultValue={block.title}
                    />
                    b
                  </div>
                  <div className="DataOutput__editing--option">
                    <label htmlFor="author">Author:</label>
                    <input
                      type="text"
                      name="author"
                      defaultValue={block.author}
                    />
                  </div>
                  <div className="DataOutput__editing--option">
                    <label htmlFor="description">Description:</label>
                    <input
                      type="text"
                      name="description"
                      defaultValue={block.description}
                    />
                  </div>
                  <div>
                    <button type="Submit">Submit</button>
                    <button
                      className="DataOutput__editing--cancel"
                      onClick={() => setEditing(null)}
                    >
                      Cancel
                    </button>
                  </div>
                </form>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
