import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

import CreateBlock from "../components/CreateBlock";
import BlocksList from "../components/BlocksList";

const StyledHeader = styled.h1`
  color: red;
`;

export default function Home() {
  const [blocks, setBlocks] = useState([]);
  const [editing, setEditing] = useState(null);

  const [blockData, setBlockData] = useState({
    height: "",
    parent: "",
    twitterURL: "",
  });
  const [proofs, setProofs] = useState([
    { amount: "", twitterURL: "", miner: "" },
  ]);

  useEffect(() => {
    getBlocks();
  }, []);

  // Create
  const onSubmitBlock = async (e) => {
    e.preventDefault();
    const builder = blockData?.twitterURL?.split("/")[3] || "";
    console.log("blockData", blockData);
    console.log("proofs", proofs);

    await axios.post("/api/blocks", {
      height: blockData.height,
      builder: builder,
      twitterURL: blockData.twitterURL,
      proofs,
    });

    // height.value = "";
    // builder.value = "";
    // twitterURL.value = "";
    // getBlocks();
  };

  // Read
  const getBlocks = async () => {
    const res = await axios.get("/api/blocks");
    const data = res.data;
    setBlocks(data);
  };

  // Update
  const onSubmitEdits = async (e, id) => {
    e.preventDefault();
    const { height, builder, twitterURL } = e.target;
    await axios.post(`/api/blocks/update/${id}`, {
      height: height.value,
      builder: builder.value,
      twitterURL: twitterURL.value,
    });
    setEditing(null);
    getBlocks();
  };

  // Delete
  const deleteBlock = async (blockToDelete) => {
    await axios({
      method: "DELETE",
      url: "/api/blocks/",
      data: {
        id: blockToDelete,
      },
    });
    await getBlocks();
  };

  return (
    <div className="App container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CreateBlock
        onSubmitBlock={onSubmitBlock}
        blockData={blockData}
        setBlockData={setBlockData}
        proofs={proofs}
        setProofs={setProofs}
      />

      <BlocksList
        blocks={blocks}
        editing={editing}
        setEditing={setEditing}
        onSubmitEdits={onSubmitEdits}
        deleteBlock={deleteBlock}
      />
    </div>
  );
}
